# Generated by Django 4.2.10 on 2024-02-11 10:33

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('techronomiblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
