name: techronomicon-build-pr

on:
  pull_request:
    types: [opened] # Trigger only when a PR is opened

permissions:
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'deploy')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/techronomicon:latest

  update-ecs-service:
    needs: build-and-push
    if: needs.build-and-push.outputs.should-deploy == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PREPROD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PREPROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: {{ secrets.PREPROD_AWS_REGION }}

      - name: Update ECS service
        run: |
          aws ecs update-service --cluster {{ secrets.PREPROD_ECS_CLUSTER_NAME}} --service {{ secrets.PREPROD_ECS_SERVICE_NAME }} --force-new-deployment
        env:
          AWS_DEFAULT_REGION: {{ secrets.PREPROD_AWS_REGION }}